### ISSUE TITLE
Add capabilities for publishing to private scoped registries. 

### ISSUE THREAD

**Issue by jlazarski** [privatenumber/npm-multi-publish#17]
In order to publish to multiple registries with private scopes, the name of the package also needs updated from @<privatereg1> /<packagename> to @<privatereg2>/<packagename>.  It would be nice if this package had that capability build in.

**Comment by privatenumber** [comment]
Thanks for the issue.

I think that's out of scope though. You can do that on your end using a lifecycle hook.
